In [55]:
import ase
import numpy as np
from ase.io import read, write

In [67]:
from ase.io import read, write

aln_unitcell = read("aln_unitcell.poscar", format='vasp')
gan_unitcell = read("gan_unitcell.poscar", format='vasp')

for fraction_al in [0.1, 0.3, 0.5, 0.7, 0.9]: # 0.0, 0.001, 0.01, 0.99, 0.999, 1.0
    fraction_ga = 1 - fraction_al

    averaged_atoms = aln_unitcell.copy()
    
    averaged_atoms.positions = aln_unitcell.positions * fraction_al + gan_unitcell.positions * fraction_ga
    
    new_cell = aln_unitcell.get_cell() * fraction_al + gan_unitcell.get_cell() * fraction_ga
    averaged_atoms.set_cell(new_cell)

    outfilename = f"averaged_{fraction_al:.1f}.poscar"
    write(outfilename, averaged_atoms, format='vasp')
    
    print(f"difference with AlN {averaged_atoms.positions - aln_unitcell.positions} for {fraction_al}Al")
    print(f"difference with GaN {averaged_atoms.positions - gan_unitcell.positions} for {fraction_al}Al")

difference with AlN [[-0.0011903   0.04985052  0.01734228]
 [ 0.04287424  0.02440985  0.12561501]
 [-0.0011903   0.04985052  0.07660659]
 [ 0.04287424  0.02440985  0.18487931]] for 0.1Al
difference with GaN [[ 0.00013226 -0.00553895 -0.00192692]
 [-0.0047638  -0.00271221 -0.01395722]
 [ 0.00013226 -0.00553895 -0.00851184]
 [-0.0047638  -0.00271221 -0.02054215]] for 0.1Al
difference with AlN [[-0.00092579  0.03877263  0.01348844]
 [ 0.03334663  0.01898544  0.09770056]
 [-0.00092579  0.03877263  0.0595829 ]
 [ 0.03334663  0.01898544  0.14379502]] for 0.3Al
difference with GaN [[ 0.00039677 -0.01661684 -0.00578076]
 [-0.01429141 -0.00813662 -0.04187167]
 [ 0.00039677 -0.01661684 -0.02553553]
 [-0.01429141 -0.00813662 -0.06162644]] for 0.3Al
difference with AlN [[-0.00066128  0.02769473  0.0096346 ]
 [ 0.02381902  0.01356103  0.06978612]
 [-0.00066128  0.02769473  0.04255921]
 [ 0.02381902  0.01356103  0.10271073]] for 0.5Al
difference with GaN [[ 0.00066128 -0.02769473 -0.0096346 ]
 [-0.0